export default {
    menuConstant: {
        PRACTICE_CENTRE: 'PRACTICE_CENTRE',
        SUB_CENTER: 'SUB_CENTER',
        PRACTICE_INSTITUTE: 'PRACTICE_INSTITUTE',
        PRACTICE_STATION: 'PRACTICE_STATION',
        PRACTICE_SITE: 'PRACTICE_SITE',
        VOLUNTEER_CORPS: 'VOLUNTEER_CORPS',
        SPECIAL_ACTIVITIES: 'SPECIAL_ACTIVITIES'
    }
}
